FROM maven:3.5-jdk-8-alpine

WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN dos2unix mvnw
RUN chmod +x mvnw
RUN ./mvnw install -DskipTests

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/javaexpress-springboot-docker.jar"]