FROM maven:3.8.7-openjdk-18-slim

WORKDIR /workspace/app

COPY pom.xml .
COPY src src

RUN mvn package -DskipTests -Dmaven.javadoc.skip=true

COPY /workspace/app/target/javaexpress-springboot-docker.jar javaexpress-springboot-docker.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","javaexpress-springboot-docker.jar"]