FROM maven:3.5-jdk-8-alpine

WORKDIR /app

COPY pom.xml .
COPY src src

#run mvn package -Dmaven.test.skip=true
run javac *.java
run jar cf JarExample.jar *.class

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/javaexpress-springboot-docker.jar"]