FROM openjdk:8-jdk-alpine AS build

WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN dos2unix mvnw
RUN chmod +x mvnw
RUN ./mvnw install -DskipTests

#JRE base image can be used here but no stable one found
FROM openjdk:8-jdk-alpine

COPY --from=build /workspace/app/target/javaexpress-springboot-docker.jar javaexpress-springboot-docker.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","javaexpress-springboot-docker.jar"]