FROM maven:3.8.7-openjdk-18-slim AS build

WORKDIR /workspace/app

COPY pom.xml .
COPY src src

RUN mvn package -DskipTests -Dmaven.javadoc.skip=true

#JRE base image can be used to reduce image size but no stable one found
FROM openjdk:8-jdk-alpine

COPY --from=build /workspace/app/target/javaexpress-springboot-docker.jar javaexpress-springboot-docker.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","javaexpress-springboot-docker.jar"]